apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: cast
  name: cast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast
  template:
    metadata:
      labels:
        app: cast
    spec:
      containers:
        - name: cast
#          image: {{ .Values.cast.image.repository }}:{{ .Values.cast.image.tag | default "latest" }}
          image: jeffka/k-cast-service:latest
          imagePullPolicy: ""
          command: ["sh", "-c", "uvicorn app.main:app --reload --host 0.0.0.0 --port 8002"]
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: cast-db-secret
                  key: DATABASE_URI
      restartPolicy: Always
