apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: cast-db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: password
  POSTGRES_USER: jeffka
  DATABASE_URI: "postgresql://jeffka:password@castdb:5432/castdb"
