apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: moviedb
  name: moviedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviedb
  template:
    metadata:
      labels:
        app: moviedb
    spec:
      containers:
        - name: moviedb
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: movie-db-configmap
            - secretRef:
                name: movie-db-secret
          volumeMounts:
            - name: movie-db-storage
              mountPath: /var/lib/postgresql/data/
  volumeClaimTemplates:
  - metadata:
      name: movie-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
