apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: moviedb
  name: moviedb
spec:
  selector:
    app: moviedb
  ports:
  - port: 5432
    targetPort: 5432
    name: "5432"
