apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: movie
  name: movie-service
spec:
  selector:
    app: movie
  ports:
    - port: 8001
      targetPort: 8001
