apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8081
      targetPort: 8081
  #    nodePort: 30081
  type: NodePort