apiVersion: v1
data:
  nginx_config.conf: |-
    server {
        listen 8081;

        location /api/v1/movies {
          proxy_pass http://movie-service:8001/api/v1/movies;
        }

        location /api/v1/casts {
          proxy_pass http://cast-service:8002/api/v1/casts;
        }

      }
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  annotations:
    use-subpath: "true"
  labels:
    app: nginx
  name: nginx-config
