# Default values for jenkinsexam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: nginx
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

cast:
  enabled: true
  image:
    repository: jeffka/k-cast-service
    tag: latest
  service:
    type: ClusterIP
    port: 8002
  env:
    DATABASE_URI: "postgresql://jeffka:password@castdb:5432/castdb"

castdb:
  enabled: true
  image:
    repository: postgres
    tag: 12.1-alpine
  service:
    type: ClusterIP
    port: 5432
  env:
    POSTGRES_DB: "castdb"
    POSTGRES_HOST_AUTH_METHOD: "trust"
    POSTGRES_USER: "jeffka"
    POSTGRES_PASSWORD: "password"

moviedb:
  enabled: true
  image:
    repository: postgres
    tag: 12.1-alpine
  service:
    type: ClusterIP
    port: 5432
  env:
    POSTGRES_DB: "moviedb"
    POSTGRES_HOST_AUTH_METHOD: "trust"


movie:
  enabled: true
  image:
    repository: jeffka/k-movie-service
    tag: latest
  service:
    type: ClusterIP
    port: 8001
  env:
    DATABASE_URI: "postgresql://jeffka:password@moviedb:5432/moviedb"

nginx:
  enabled: true
  image:
    repository: nginx
    tag: latest
  service:
    type: NodePort
    port: 8081
  configMap:
    nginx.conf: |
      server {
        listen 8081;

        location /api/v1/movies {
          proxy_pass http://movie-service:8001/api/v1/movies;
        }

        location /api/v1/casts {
          proxy_pass http://cast-service:8002/api/v1/casts;
        }

      }